name = "randomrooms"
main = "worker.js"
compatibility_date = "2025-02-11"
workers_dev = true
routes = ["randomrooms.info/*", "www.randomrooms.info/*"]

[durable_objects]
bindings = [
  { name = "ROOM_DO", class_name = "RoomDurableObject" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["RoomDurableObject"]
